config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  resources :articles
  resources :categories
  resources :sub_categories

  root 'categories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :sub_category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :sub_categories, dependent: :destroy

end

app/models/ckeditor/asset.rb
# frozen_string_literal: true

class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
# frozen_string_literal: true

class Ckeditor::AttachmentFile < Ckeditor::Asset
  # for validation, see https://github.com/igorkasyanchuk/active_storage_validations

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
# frozen_string_literal: true

class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/sub_category.rb
class SubCategory < ApplicationRecord
  belongs_to :category

  has_many :articles, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:show]
  before_action :set_sub_categories, only: [:show]
  before_action :set_articles, only: [:show]
  before_action :set_sub_categories_options, only: [:edit, :new]

  def index
    redirect_to categories_path
    return
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :content, :sub_category_id)
    end

    def set_categories
      @categories = Category.all
    end

    def set_sub_categories
      @sub_categories = SubCategory.where(category: @article.sub_category.category)
    end

    def set_articles
      @articles = Article.where(sub_category: @article.sub_category)
    end

    def set_sub_categories_options
      @sub_categories = SubCategory.includes(:category).all.map{ |sub_cat| ["#{sub_cat.category.name} | #{ sub_cat.name}", sub_cat.id] }
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:show, :index]
  before_action :set_sub_categories, only: [:show]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end

    def set_categories
      @categories = Category.all
    end

    def set_sub_categories
      @sub_categories = SubCategory.where(category: @category)
    end
  end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  before_action :set_sub_category, only: [:show, :edit, :update, :destroy]
  before_action :set_categories, only: [:show]
  before_action :set_articles, only: [:show]
  before_action :set_sub_categories, only: [:show]

  # GET /sub_categories
  # GET /sub_categories.json
  def index
    @sub_categories = SubCategory.all
  end

  # GET /sub_categories/1
  # GET /sub_categories/1.json
  def show
  end

  # GET /sub_categories/new
  def new
    @sub_category = SubCategory.new
  end

  # GET /sub_categories/1/edit
  def edit
  end

  # POST /sub_categories
  # POST /sub_categories.json
  def create
    @sub_category = SubCategory.new(sub_category_params)

    respond_to do |format|
      if @sub_category.save
        format.html { redirect_to @sub_category, notice: 'Sub category was successfully created.' }
        format.json { render :show, status: :created, location: @sub_category }
      else
        format.html { render :new }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_categories/1
  # PATCH/PUT /sub_categories/1.json
  def update
    respond_to do |format|
      if @sub_category.update(sub_category_params)
        format.html { redirect_to @sub_category, notice: 'Sub category was successfully updated.' }
        format.json { render :show, status: :ok, location: @sub_category }
      else
        format.html { render :edit }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_categories/1
  # DELETE /sub_categories/1.json
  def destroy
    @sub_category.destroy
    respond_to do |format|
      format.html { redirect_to sub_categories_url, notice: 'Sub category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_category
      @sub_category = SubCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sub_category_params
      params.require(:sub_category).permit(:name, :category_id)
    end

    def set_categories
      @categories = Category.all
    end

    def set_sub_categories
      @sub_categories = SubCategory.where(category: @sub_category.category)
    end

    def set_articles
      @articles = Article.where(sub_category: @sub_category)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/articles/_article.html.erb
<%= link_to article do %>
  <div class="list-item article <%= active ? 'active' : '' %>">
    <%= article.title.present? ? article.title : 'N/A' %>
  </div>
<% end %>

app/views/articles/_category.html.erb
<%= link_to category do %>
  <div class="list-item category <%= active ? 'active' : '' %>">
    <%= category.name %>
  </div>
<% end %>

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :sub_category_id %>
    <%= form.select :sub_category_id, @sub_categories %>
  </div>

  <div class="field">
    <%= form.cktext_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/_sub_category.html.erb
<%= link_to sub_category do %>
  <div class="list-item sub-category <%= active ? 'active' : '' %>">
    <%= sub_category.name %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="edit-article">
  <div class="heading">Editing Article</div>

  <%= render 'form', article: @article %>

  <%= link_to 'Show', @article %> |
  <%= link_to 'Back', articles_path %>
</div>

app/views/articles/index.html.erb
<div class="article">
  <div class="menu-bar">
    <div class="list-container categories">
      <div class="heading">Categories</div>
      <% @categories.each do |category| %>
        <%= render partial: 'category', locals: { category: category, active: category == @article.sub_category.category }%>
      <% end %>
    </div>
    <div class="list-container sub-categories">
      <div class="heading">Sub Categories</div>
      <% @sub_categories.each do |sub_category| %>
        <%= render partial: 'sub_category', locals: { sub_category: sub_category, active: sub_category == @article.sub_category }%>
      <% end %>
    </div>
    <div class="list-container articles-list">
      <div class="heading">Articles</div>
      <% @articles.each do |article| %>
        <%= render partial: 'article', locals: { article: article, active: article == @article }%>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="edit-article">
  <div class="heading">New Article</div>

  <%= render 'form', article: @article %>

  <%= link_to 'Back', articles_path %>
</div>

app/views/articles/show.html.erb
<div class="article">
  <div class="menu-bar">
    <div class="list-container categories">
      <div class="heading">Categories</div>
      <% @categories.each do |category| %>
        <%= render partial: 'category', locals: { category: category, active: category == @article.sub_category.category }%>
      <% end %>
    </div>
    <div class="list-container sub-categories">
      <div class="heading">Sub Categories</div>
      <% @sub_categories.each do |sub_category| %>
        <%= render partial: 'sub_category', locals: { sub_category: sub_category, active: sub_category == @article.sub_category }%>
      <% end %>
    </div>
    <div class="list-container articles-list">
      <div class="heading">Articles</div>
      <% @articles.each do |article| %>
        <%= render partial: 'article', locals: { article: article, active: article == @article }%>
      <% end %>
    </div>
  </div>
  <div class="article-container">
    <div class="heading-container">
      <div class="heading"><%= @article.title %></div>
      <hr/>
      <div class="date"><%= @article.updated_at.strftime("%A, %e %B %Y")%></div>
      <div class="time"><%= @article.updated_at.strftime("%I:%M %p")%></div>
      <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-primary' %>
      <%= link_to 'New', new_article_path, class: 'btn btn-primary' %>
    </div>
    <div class="content">
      <%= @article.content.html_safe %>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="article">
  <div class="menu-bar">
    <div class="list-container categories">
      <div class="heading">Categories</div>
      <% @categories.each do |category| %>
        <%= render partial: 'articles/category', locals: { category: category, active: false }%>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="article">
  <div class="menu-bar">
    <div class="list-container categories">
      <div class="heading">Categories</div>
      <% @categories.each do |category| %>
        <%= render partial: 'articles/category', locals: { category: category, active: category == @category }%>
      <% end %>
    </div>
    <div class="list-container sub-categories">
      <div class="heading">Sub Categories</div>
      <% @sub_categories.each do |sub_category| %>
        <%= render partial: 'articles/sub_category', locals: { sub_category: sub_category, active: false }%>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KnowledgeBase</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag Ckeditor.cdn_url %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sub_categories/_form.html.erb
<%= form_with(model: sub_category, local: true) do |form| %>
  <% if sub_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sub_category.errors.count, "error") %> prohibited this sub_category from being saved:</h2>

      <ul>
      <% sub_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sub_categories/edit.html.erb
<h1>Editing Sub Category</h1>

<%= render 'form', sub_category: @sub_category %>

<%= link_to 'Show', @sub_category %> |
<%= link_to 'Back', sub_categories_path %>

app/views/sub_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sub Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sub_categories.each do |sub_category| %>
      <tr>
        <td><%= sub_category.name %></td>
        <td><%= sub_category.category %></td>
        <td><%= link_to 'Show', sub_category %></td>
        <td><%= link_to 'Edit', edit_sub_category_path(sub_category) %></td>
        <td><%= link_to 'Destroy', sub_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sub Category', new_sub_category_path %>

app/views/sub_categories/new.html.erb
<h1>New Sub Category</h1>

<%= render 'form', sub_category: @sub_category %>

<%= link_to 'Back', sub_categories_path %>

app/views/sub_categories/show.html.erb
<div class="article">
  <div class="menu-bar">
    <div class="list-container categories">
      <div class="heading">Categories</div>
      <% @categories.each do |category| %>
        <%= render partial: 'articles/category', locals: { category: category, active: category == @sub_category.category }%>
      <% end %>
    </div>
    <div class="list-container sub-categories">
      <div class="heading">Sub Categories</div>
      <% @sub_categories.each do |sub_category| %>
        <%= render partial: 'articles/sub_category', locals: { sub_category: sub_category, active: sub_category == @sub_category }%>
      <% end %>
    </div>
    <div class="list-container articles-list">
      <div class="heading">Articles</div>
      <% @articles.each do |article| %>
        <%= render partial: 'articles/article', locals: { article: article, active: false }%>
      <% end %>
    </div>
  </div>
</div>